✨ Add support for Cadence struct to Go struct
ritz078/transform pull request #338
Opened 2022-08-14 14:04 UTC by LemonNekoGH

2022-08-14 14:10 UTC, ritz078 commented
#### 📝 Changed routes:


| [**/cadence-to-go**](https://transform-wdiymg037-ritz078.vercel.app/cadence-to-go) |
|:-:|
|<a href="https://transform-wdiymg037-ritz078.vercel.app/cadence-to-go"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/NvuqW1eJMbKvcwV3P8fQR8g9gaZ_tu07t9qEix7JSZvAeo4Mp9KywvuEQu-JQ5_C_tlmq228lJyWDrOy-ZaEjg.png&w=600" alt="Screenshot of /cadence-to-go" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7cspxp7ygZOp1Y3SMsxjfcyj5uHArcKriSBYVhsGr3vMmHBh0wvAX7BNaYYWiQG1qpvy_EJmsCIiWxo1-vPmsg.png">(view full size)</a> |







Commit ca26a260398c1ceb0fe698ab919b5dbf0f06d654 (https://transform-wdiymg037-ritz078.vercel.app).

2022-08-15 12:20 UTC, ritz078 commented on pages/cadence-to-go.tsx
> +      editorLanguage="cadence"
Cadence is not supported by Monaco editor so you should change this to "text"

2022-08-15 12:21 UTC, ritz078 requested changes
I have added a few comments for your consideration. Thank you.

2022-08-15 12:21 UTC, ritz078 commented on pages/cadence-to-go.tsx
> +    console.log(dec)
```suggestion
```

2022-08-15 12:21 UTC, ritz078 commented on pages/cadence-to-go.tsx
> +  console.log(ret)
```suggestion
```

2022-10-13 15:38 UTC, ritz078 commented
Sorry for the (very) late response. Thank you for your contribution 🎉

2022-10-13 15:38 UTC, ritz078 approved these changes

2022-10-13 15:38 UTC, merged

2022-10-13 15:39 UTC, ritz078 commented
@allcontributors please add @LemonNekoGH for code.

2023-01-12 03:35 UTC, LemonNekoGH commented
Thank you!